version: '3.8'

services:
  backend:
    container_name: moveshare-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      - database
      - minio
    networks:
      - default


  database:
    container_name: movingshare-database
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - db-data:/var/lib/postgresql/data  
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:80"
    networks:
      - default


  minio:
    container_name: movingshare-minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: unless-stopped
    env_file:
      - ./.env
    # volumes:
    #   - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - default


volumes:
  db-data:


networks:
  default:
    driver: bridge