CREATE TABLE jobs (
    id SERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    job_title TEXT NOT NULL,
    description TEXT,
    cargo_type TEXT,
    urgency TEXT,
    pickup_location TEXT NOT NULL,
    delivery_location TEXT NOT NULL,
    weight_lb DOUBLE PRECISION,
    volume_cu_ft DOUBLE PRECISION,
    truck_size TEXT,
    loading_assistance BOOLEAN DEFAULT FALSE,
    pickup_date DATE,
    pickup_time_window TEXT,
    delivery_date DATE,
    delivery_time_window TEXT,
    payout_amount DOUBLE PRECISION,
    early_delivery_bonus DOUBLE PRECISION,
    payment_terms TEXT,
    liftgate BOOLEAN DEFAULT FALSE,
    fragile_items BOOLEAN DEFAULT FALSE,
    climate_control BOOLEAN DEFAULT FALSE,
    assembly_required BOOLEAN DEFAULT FALSE,
    extra_insurance BOOLEAN DEFAULT FALSE,
    additional_packing BOOLEAN DEFAULT FALSE,
    status TEXT DEFAULT 'available',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    distance_miles DOUBLE PRECISION,
    
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
